import type { Metadata } from "next"
import { Geist, Inter } from "next/font/google"
import type { ReactNode } from "react"

import "@/styles/app.css"

import { ThemeProvider } from "next-themes"
import { Providers } from "@/components/providers"
import { cn } from "@/lib/utils"

const inter = Inter({subsets:['latin'],variable:'--font-sans'})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("font-sans", inter.variable)}
    >
      <body className="antialiased min-h-svh flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>

            {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  )
}